apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 4
  activeDeadlineSeconds: 240
  template:
    spec:
      containers:
      - name: test-job
        image: maven:3.6.0-jdk-11-slim
        command: ["mvn", "test"]          
      restartPolicy: Never
