apiVersion: apps/v1
kind: Deployment
{{- with .Values }}
metadata:
  name: "{{ include "app.name" . }}-deployment"
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .image.gcrImageLoc }}"
        ports:
            - name: {{ .service.name }}
              containerPort: {{ .service.port }}
              protocol: TCP
{{- end }}
