apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name}}-server"
  labels:
    app: {{ .Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
      - name: {{ .Values.name}}
        image: "{{ .Values.image.gcrImageLoc }}"
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
