apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-helm-hello-server
  labels:
    app: sg-helm-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sg-helm-hello
  template:
    metadata:
      labels:
        app: sg-helm-hello
    spec:
      containers:
      - name: sg-helm-hello
        image: gcr.io/shaped-kite-284918/sample-helm-helloworld:v1
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
