apiVersion: apps/v1
kind: Deployment
metadata:
  name: sg-hello-helm-server
  labels:
    app: sg-hello-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sg-hello-helm
  template:
    metadata:
      labels:
        app: sg-hello-helm
    spec:
      containers:
      - name: sg-hello-helm
        image: gcr.io/shaped-kite-284918/sg-hello-helm-server:v1
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
