apiVersion: v1
kind: Service
metadata:
  name: sg-hello-helm-server
  labels:
    app: sg-hello-helm
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sg-hello-helm
