apiVersion: v1
kind: Service
{{- with .Values }}
metadata:
  name: "{{ include "app.name" . }}-service"
  labels:
    app: {{ .name}}
spec:
  type: {{ .service.type}}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .service.name }}
  selector:
    app: {{ .name }}
{{- end }}
